export const comandsList = [
    "about",
    "boreal",
    "boreal apax",
    "current",
    "damng",
    "dielucard",
    "education",
    "email",
    "fire",
    "github",
    "help",
    "home",
    "i-am-your-father",
    "linkedin",
    "metal",
    "mia",
    "oriadris",
    "portfolio",
    "professional",
    "padaone",
    "padaone web",
    "personal",
    "planet",
    "sudo",
    "spanish",
    "treeventure",
    "twitter",
];